/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otelrezervasyonu;

import java.awt.Button;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static otelrezervasyonu.DbConnect.dbBaglanti;

/**
 *
 * @author developer
 */
public class MusterilerSayfasi extends javax.swing.JFrame {

        public Anasayfa anasayfa;
       static  ArrayList<Musteri> musteriler=new ArrayList<Musteri>();
        public static  boolean rezervasyonYap;

    /**
     * Creates new form MusterilerSayfasi
     */
    public MusterilerSayfasi() {
        initComponents();
        rezervasyonYap=false;
        String sorgu="select * from aktifMusteriler";
        musteriListele(sorgu);
    }

    
     public  static  void musteriListele(String sorgu){
        DefaultTableModel model;
        musteriler.clear();
        Statement state=null;
        ResultSet rs=null;
         model=(DefaultTableModel)tblTumMusteriler.getModel();
                 model.setRowCount(0);        
       try{
            state=dbBaglanti().createStatement();
            rs=state.executeQuery(sorgu);
            
            while(rs.next()){
                int m_id=rs.getInt("aMusteri_id");
                String m_adi=rs.getString("aMusteri_adi");
                String m_soyadi=rs.getString("aMusteri_soyadi");     
                int m_yas=rs.getInt("aMusteri_yas");
                String m_tc=rs.getString("aMusteri_tc");
                String  m_tel=rs.getString("aMusteri_tel");
                String m_meslek=rs.getString("aMusteri_meslek");
                
                musteriler.add(new Musteri(m_id,m_adi,m_soyadi,m_yas,m_meslek,m_tc,m_tel));
            }
                                      DbConnect.dbBaglanti().close();

             if(musteriler!=null){                    
                    for(Musteri musteri:musteriler){       
                        
                        Object[] add={musteri.getAd(),musteri.getSoyad(),musteri.getTc(),musteri.getYas(),musteri.getTel(),musteri.getMeslegi()};
                                            model.addRow(add);                  
                    }
             }
                                 tblTumMusteriler.setModel(model);             
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
      

        
    
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtMusteriArama = new javax.swing.JTextField();
        btnMusteriEkle = new javax.swing.JButton();
        btnMusteriDuzenleme = new javax.swing.JButton();
        btnMusteriSil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTumMusteriler = new javax.swing.JTable();
        btnilerle = new javax.swing.JButton();
        btnGeri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtMusteriArama.setText("Müşteri Adı Soyadı veya Tc Numarasi  ile Arama Yapmak için Tıkayın..");
        txtMusteriArama.setToolTipText("Oda Numarası veya Oda Tipi ile Arama Yapmak için Tıkayın..");
        txtMusteriArama.setFocusTraversalPolicyProvider(true);
        txtMusteriArama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMusteriAramaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMusteriAramaFocusLost(evt);
            }
        });
        txtMusteriArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMusteriAramaKeyReleased(evt);
            }
        });

        btnMusteriEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add-icon.png"))); // NOI18N
        btnMusteriEkle.setText("Müşteri Ekle");
        btnMusteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusteriEkleActionPerformed(evt);
            }
        });

        btnMusteriDuzenleme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-validated-icon.png"))); // NOI18N
        btnMusteriDuzenleme.setText("Düzenle");
        btnMusteriDuzenleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusteriDuzenlemeActionPerformed(evt);
            }
        });

        btnMusteriSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Close-icon.png"))); // NOI18N
        btnMusteriSil.setText("Sil");
        btnMusteriSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusteriSilActionPerformed(evt);
            }
        });

        tblTumMusteriler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adı", "Soyadı", "TC", "Yaş", "Telefon", "Meslek"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTumMusteriler.setRowHeight(30);
        tblTumMusteriler.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblTumMusteriler);

        btnilerle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ileri.png"))); // NOI18N
        btnilerle.setText("İlerle ");
        btnilerle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnilerleActionPerformed(evt);
            }
        });

        btnGeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/geri.png"))); // NOI18N
        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtMusteriArama, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGeri, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnilerle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMusteriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMusteriDuzenleme, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMusteriSil, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMusteriArama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeri, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnilerle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMusteriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMusteriDuzenleme, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMusteriSil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMusteriAramaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMusteriAramaFocusGained
        // TODO add your handling code here:
        if(txtMusteriArama.getText().equals("Müşteri Adı Soyadı veya Tc Numarasi  ile Arama Yapmak için Tıkayın..")){
            txtMusteriArama.setText("");
        }
        

    }//GEN-LAST:event_txtMusteriAramaFocusGained

    private void txtMusteriAramaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMusteriAramaFocusLost
        // TODO add your handling code here:
        if(txtMusteriArama.getText().equals("") ){
            txtMusteriArama.setText("Müşteri Adı Soyadı veya Tc Numarasi  ile Arama Yapmak için Tıkayın..");
        }

    }//GEN-LAST:event_txtMusteriAramaFocusLost

    private void txtMusteriAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMusteriAramaKeyReleased
        // TODO add your handling code here:
       
          //  String sorgu="select  aMusteri_id, aMusteri_adi,aMusteri_soyadi,aMusteri_tc,aMusteri_yas,aMusteri_tel,aMusteri_meslek , CONCAT(aktifMusteriler.aMusteri_adi,"+"  "+",aktifMusteriler.aMusteri_soyadi) as "+ "adSoyad"+"    from aktifMusteriler where  CONCAT(aktifMusteriler.aMusteri_adi,"+" "+",aktifMusteriler.aMusteri_soyadi) LIKE '%"+txtMusteriArama.getText()+"%'    or  aMusteri_tc like '%"+txtMusteriArama.getText()+"%' ";
         String sorgu="select  aMusteri_id, aMusteri_adi,aMusteri_soyadi,aMusteri_tc,aMusteri_yas,aMusteri_tel,aMusteri_meslek    from aktifMusteriler where  aktifMusteriler.aMusteri_adi LIKE '%"+txtMusteriArama.getText()+"%' or aktifMusteriler.aMusteri_soyadi  LIKE '%"+txtMusteriArama.getText()+"%'    or  aMusteri_tc like '%"+txtMusteriArama.getText()+"%' ";

            musteriListele(sorgu);
       
       
    }//GEN-LAST:event_txtMusteriAramaKeyReleased

    private void btnMusteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusteriEkleActionPerformed
        // TODO add your handling code here:
        MusteriIslemler islemler=new MusteriIslemler();
        this.setAlwaysOnTop(false);
                islemler.setAlwaysOnTop(true);
                    
        islemler.setVisible(true);
        islemler.btnMusteriGuncelle.setVisible(false);
         islemler.btnMusteriKaydet.setVisible(true);

        
    }//GEN-LAST:event_btnMusteriEkleActionPerformed

    private void btnMusteriDuzenlemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusteriDuzenlemeActionPerformed
        // TODO add your handling code here:
        if(tblTumMusteriler.getSelectedRow()>=0){
             MusteriIslemler islemler=new MusteriIslemler();
                this.setAlwaysOnTop(false);
          islemler.setAlwaysOnTop(true);
          islemler.setVisible(true);
          DefaultTableModel model;
       int i=tblTumMusteriler.getSelectedRow();
       
       //düzenle butonuna basınca  seçilli musterinin bilgilerini islemler sayfasındaki kutulara atadım
        islemler.btnMusteriGuncelle.setVisible(true);
         islemler.btnMusteriKaydet.setVisible(false);
         islemler.txtMusteriAdi.setText(musteriler.get(i).getAd());
         islemler.txtMusteriSoyadi.setText(musteriler.get(i).getSoyad());
         islemler.txtTC.setText(musteriler.get(i).getTc());
         islemler.txtYas.setText(musteriler.get(i).getYas()+"");
         islemler.txtTelefon.setText(musteriler.get(i).getTel());
         islemler.txtMeslek.setText(musteriler.get(i).getMeslegi());
         islemler.m_id=musteriler.get(i).getM_id();
        }
       
    }//GEN-LAST:event_btnMusteriDuzenlemeActionPerformed

    private void btnMusteriSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusteriSilActionPerformed
        // TODO add your handling code here:
                   int i=tblTumMusteriler.getSelectedRow();

       if( JOptionPane.showConfirmDialog(null, musteriler.get(i).getAd()+ " "+musteriler.get(i).getSoyad()+" isimli Müşteriyi silmek istiyormusunuz?", "Uyarı" ,0)==JOptionPane.YES_OPTION){
           int id=musteriler.get(i).getM_id();
           
           Statement st=null;
           
           try{
               String sorgu="delete  from aktifMusteriler where aMusteri_id="+id+" ";
               st=dbBaglanti().createStatement();
               int sonuc=st.executeUpdate(sorgu);
                                         DbConnect.dbBaglanti().close();

               if(sonuc==1){
                   JOptionPane.showMessageDialog(null,"Müşteri Silindi");
                          sorgu="select * from aktifMusteriler";

                   musteriListele(sorgu);

               }
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
           
           
       }
                
    }//GEN-LAST:event_btnMusteriSilActionPerformed

    private void btnilerleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnilerleActionPerformed
        // TODO add your handling code here:
        if(tblTumMusteriler.getSelectedRow()>=0){
            RezervasyonYap.m_id=musteriler.get(tblTumMusteriler.getSelectedRow()).getM_id();
              RezervasyonYap.mAdi=musteriler.get(tblTumMusteriler.getSelectedRow()).getAd();
        RezervasyonYap.mSoyadi=musteriler.get(tblTumMusteriler.getSelectedRow()).getSoyad();
        RezervasyonYap.mYas=musteriler.get(tblTumMusteriler.getSelectedRow()).getYas();
        RezervasyonYap rezervasyon=new RezervasyonYap();
        rezervasyon.setVisible(true);
        this.dispose();
        }
      
    }//GEN-LAST:event_btnilerleActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(rezervasyonYap)
        {
            btnilerle.setVisible(true);
            btnGeri.setVisible(true);
            btnMusteriDuzenleme.setVisible(false);
            btnMusteriSil.setVisible(false);
        }
        else{
            btnGeri.setVisible(false);
            btnilerle.setVisible(false);
            btnMusteriDuzenleme.setVisible(true);
            btnMusteriSil.setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnGeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusterilerSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusterilerSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusterilerSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusterilerSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusterilerSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnMusteriDuzenleme;
    private javax.swing.JButton btnMusteriEkle;
    private javax.swing.JButton btnMusteriSil;
    private javax.swing.JButton btnilerle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tblTumMusteriler;
    private javax.swing.JTextField txtMusteriArama;
    // End of variables declaration//GEN-END:variables
}
