/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otelrezervasyonu;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author developer
 */
public class OdaServisiSayfasi extends javax.swing.JFrame {

    
    public int Rezervasyon_id;
    /**
     * Creates new form OdaServisi
     */
    public OdaServisiSayfasi() {
        initComponents();
        yiyecekIceceklerGetir();
    }
    
    ArrayList<OdaServisi> icecekler=new ArrayList<OdaServisi>();
        ArrayList<OdaServisi> yiyecekler=new ArrayList<OdaServisi>();

public void yiyecekIceceklerGetir(){
    DefaultListModel model=new DefaultListModel();
        DefaultListModel model2=new DefaultListModel();

    String sorgu="select * from odaServisi";
        Statement state=null;
       ResultSet rs=null;
      
        try{
           state=DbConnect.dbBaglanti().createStatement();
          rs=state.executeQuery(sorgu);
          while(rs.next()){
              int id=rs.getInt("odaServisi_id");
                String urun_adi=rs.getString("urun_adi");
                double urun_fiyati=rs.getDouble("urun_fiyati");
                int tur=rs.getInt("tur");
                Object[] add={urun_adi,urun_fiyati,tur};
                if( add[2].equals(0)){
                    //yiyecek
                    model.addElement(add[0]+"..............."+add[1]);
                    listYiyecekler.setModel(model);
                                    yiyecekler.add(new OdaServisi(id,urun_adi,urun_fiyati,tur));

                }
                else if(add[2].equals(1)){
                     model2.addElement(add[0]+"..............."+add[1]);
                    listIcecekler.setModel(model2);
                                    icecekler.add(new OdaServisi(id,urun_adi,urun_fiyati,tur));
                                   

                    //içecek
                }
           }  //while finish
                                    DbConnect.dbBaglanti().close();

         
               
          
        
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
}
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listIcecekler = new javax.swing.JList<>();
        btnOdayaGonder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listYiyecekler = new javax.swing.JList<>();
        lblToplam = new javax.swing.JLabel();
        lblToplam1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Yiyecek İçecekler");

        listIcecekler.setBorder(javax.swing.BorderFactory.createTitledBorder("İçecekler"));
        listIcecekler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listIcecekler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listIceceklerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listIcecekler);

        btnOdayaGonder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/telegram-icon.png"))); // NOI18N
        btnOdayaGonder.setText("Odaya Gönder");
        btnOdayaGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdayaGonderActionPerformed(evt);
            }
        });

        listYiyecekler.setBorder(javax.swing.BorderFactory.createTitledBorder("Yiyecekler"));
        listYiyecekler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listYiyecekler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listYiyeceklerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listYiyecekler);

        lblToplam.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblToplam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblToplam.setText("0");

        lblToplam1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblToplam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblToplam1.setText("TL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnOdayaGonder, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(lblToplam, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblToplam1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblToplam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblToplam1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOdayaGonder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
            double yiyecekToplam;
            double icecekToplam;
    private void listYiyeceklerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listYiyeceklerMouseClicked
        // TODO add your handling code here:
        int indices[]=listYiyecekler.getSelectedIndices();
        yiyecekToplam=0;
        lblToplam.setText("0");
        for (int i = 0; i <indices.length; i++) {
            yiyecekToplam+=yiyecekler.get(indices[i]).getUrun_fiyati();
        }
       lblToplam.setText( "" +(yiyecekToplam+icecekToplam)  );
        
    }//GEN-LAST:event_listYiyeceklerMouseClicked

    private void listIceceklerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listIceceklerMouseClicked
        // TODO add your handling code here:
        
        int indices[]=listIcecekler.getSelectedIndices();
        icecekToplam=0;
                lblToplam.setText("0");

        for (int i = 0; i <indices.length; i++) {
            icecekToplam+=icecekler.get(indices[i]).getUrun_fiyati();
               

        }
               lblToplam.setText( "" +(yiyecekToplam+icecekToplam)  );
               ;

    }//GEN-LAST:event_listIceceklerMouseClicked

    private void btnOdayaGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdayaGonderActionPerformed
        // TODO add your handling code here:
        int indices1[]=listIcecekler.getSelectedIndices();  //  0 /1
        int indices2[]=listYiyecekler.getSelectedIndices();  //0/1
        int [] odaServisi_id=new int[(indices1.length+indices2.length)];
        
        for (int i = 0; i <odaServisi_id.length ; i++) {
            //icecekler
            if(indices1.length>0){
                            odaServisi_id[i]=icecekler.get(indices1[i]).getOdaServisi_id();

            }

            if(i>= (indices1.length-1) ){
                //yiyecekler   
                    for (int j = 0; j < indices2.length; j++) {
                     
                           odaServisi_id[indices1.length+j]=yiyecekler.get(indices2[j]).getOdaServisi_id();

                }
                    break;
            }
                
            }
        
      int sonuc=  OtelTest.odaServisi(Double.parseDouble(lblToplam.getText()),Rezervasyon_id,odaServisi_id);
      
      if(sonuc==1){
          this.setAlwaysOnTop(false);
          JOptionPane.showMessageDialog(null,"Servis Odaya Gönderildi");
         String sorgu="select Rezervasyon.rezervasyon_id,musteriler.musteri_adi,musteriler.musteri_soyadi,otelOdalari.oda_numarasi,RezervasyonTipleri.RezervasyonTipi, Rezervasyon.kisiSayisi,Rezervasyon.toplamFiyat FROM Rezervasyon JOIN musteriler on musteriler.musteri_id=Rezervasyon.musteri_id JOIN otelOdalari on otelOdalari.oda_id=Rezervasyon.oda_id JOIN RezervasyonTipleri on  RezervasyonTipleri.RTipleri_id=Rezervasyon.RezervasyonTipi_id  GROUP BY Rezervasyon.rezervasyon_id DESC";
        Rezervasyon.rezervasyonGoster(sorgu);
        this.dispose();
      }
    }//GEN-LAST:event_btnOdayaGonderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OdaServisiSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OdaServisiSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OdaServisiSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OdaServisiSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OdaServisiSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdayaGonder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblToplam;
    private javax.swing.JLabel lblToplam1;
    private javax.swing.JList<String> listIcecekler;
    private javax.swing.JList<String> listYiyecekler;
    // End of variables declaration//GEN-END:variables
}
